console.log("------------------------------------True Statement----------------------------------");
var n = 8;
console.log(n == 8 ? true : false);
console.log(n);
var cars = 'Mercedes';
console.log(cars == 'Mercedes' ? true : false);
console.log(cars);
var bike = 'Ducati';
console.log(bike == 'Ducati' ? true : false);
console.log(bike);
var jet = 'JF-17';
console.log(jet == 'JF-17' ? true : false);
console.log(jet);
var ship = 'Titanic';
console.log(ship == 'Titanic' ? true : false);
console.log(ship);
console.log("------------------------------------False Statement----------------------------------");
console.log(n == 6 ? true : false);
console.log(n);
console.log(cars == 'Audi' ? true : false);
console.log(cars);
console.log(bike == 'Honda' ? +true : false);
console.log(bike);
console.log(jet == 'F-16' ? true : false);
console.log(jet);
console.log(ship == 'WarShip' ? true : false);
console.log(ship);
// In True statemnet the strings were matched whereas in false statements they didn't!
